

spring:
  application:
    name: loan
  server:
  port : 9000
  
  database: h2
  console: true
  path: /h2

datasource:
  platform: h2
  url: jdbc:h2://localhost:8080/h2
  username: sa
  password: password
  driverClassName: org.h2.Driver
  cloud:
    config:
      uri: http://localhost:8888
  discovery:
    client:
      simple:
        enabled: true