spring:
  application:
    name: admin
    
  database: h2
  console: true
  path: /h2

datasource:
  platform: h2
  url: jdbc:h2://localhost:8080/h2
  username: sa
  password: 1234
  driverClassName: org.h2.Driver
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    config:
      uri: http://localhost:8888
  discovery:
    client:
      simple:
        enabled: true